### PR TITLE
Feature/test get rabbit message

### PR DESCRIPTION
**Pull request by MShel**
Test creation: get_rabbit_message #254

also fixed the return in poseidonMonitor.py + double unpacking

### CODE REVIEW

**Comment by cglewis** [comment]
@MShel conflicts need to be resolved before this can be merged.

**Comment by MShel** [comment]
please merge that on as the last one...

**Comment by cglewis** [comment]
@d-grossman do you mind checking that this is in the intended return value you're expecting?

**Comment by d-grossman** [comment]
Hopefully I will check it out Monday or next week because of travel.

**Comment by d-grossman** [comment]
I think that it is functionally the same.

**Pull request merged**
