### PR TITLE
explain makefile options

### PR DESCRIPTION
**Pull request by 1uka**
update readme to explain Makefile options, issue #349

### CODE REVIEW

**Comment by cglewis** [comment]
@1uka was there something wrong with this that you closed it?

**Comment by 1uka** [comment]
@cglewis well, just after i opened it i saw someone else also opened a pull request for the same issue, and i thought "eh, it must be better than mine",  and this is my first time contributing. i am sorry if i wasnt supposed to, if you want i will open it again 😄

**Comment by cglewis** [comment]
the other one was changing the makefile, not writing the documentation - absolutely reopen it and I'll review it :)

**Comment by 1uka** [comment]
@cglewis oh, great! i messed up something in the meantime, and the reopen and comment button is dimmed so i will reopen the same pull request again. sorry if i polluted your repository with my goofiness

**Comment by cglewis** [comment]
nope, no problem at all.  thanks for contributing!

**Pull request closed without merging**
